    "ffmpeg",
    "-re",
    "-i", playback_url,
    "-c:v", "libx264",
    "-preset", "veryfast",
    "-maxrate", "4500k",
    "-bufsize", "9000k",
    "-pix_fmt", "yuv420p",
    "-g", "60",
    "-c:a", "aac",
    "-b:a", "128k",
    "-ar", "44100",
    "-f", "flv",
    rtmp_url
